<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
/** @var \Tigren\SimpleBlog\Block\Category $block */
?>
<?php $posts = $block->getPostItems(); ?>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }


</style>
<div class="post-content">
    <table style="width:100%">
        <tr>
            <th><?php echo __('Name') ?></th>
            <th><?php echo __('Description') ?></th>
        </tr>
        <?php if (count($posts)) : ?>
            <?php foreach ($posts as $post) : ?>
                <tr>
                    <td>
                        <a href="<?php echo $block->getUrl("simpleblog/index/lists/") . "tigren_blog_category_id/" . $post->getTigrenBlogCategoryId() ?>"><?php echo $post->getName() ?></a>
                    </td>
                    <td><?php echo $post->getDescription() ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>
