<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
/** @var \Tigren\SimpleBlog\Block\Detail $block */
?>
<?php $posts = $block->getPostItems();
$p = $posts->getData();
//dd($posts->getData()); ?>
<style>
    * {
        box-sizing: border-box;
    }

    body {
        font-family: Arial;
        padding: 20px;
        background: #f1f1f1;
    }

    /* Header/Blog Title */
    #header {
        padding: 30px;
        font-size: 40px;
        text-align: center;
        background: white;
    }

    /* Create two unequal columns that floats next to each other */
    /* Left column */
    .leftcolumn {
        float: left;
        width: 75%;
    }

    /* Right column */
    .rightcolumn {
        float: left;
        width: 25%;
        padding-left: 20px;
    }

    /* Fake image */
    .fakeimg {
        background-color: #aaa;
        width: 100%;
        padding: 20px;
    }

    /* Add a card effect for articles */
    .card {
        background-color: white;
        padding: 20px;
        margin-top: 20px;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }

    /* Footer */
    .footer {
        padding: 20px;
        text-align: center;
        background: #ddd;
        margin-top: 20px;
    }

    /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 800px) {
        .leftcolumn, .rightcolumn {
            width: 100%;
            padding: 0;
        }
    }
</style>
<div id="header">
    <h2><?php echo $p['title'] ?></h2>
</div>

<div class="row">
    <div class="leftcolumn">
        <div class="card">
            <h2><?php echo $p['short_content'] ?></h2>
            <h5><?php echo $p['author'] ?>, <?php echo $p['published_at'] ?></h5>
            <div class="fakeimg">
                <img src="<?php echo $block->getUrl("pub/media/catalog/tmp/category/") . $p['post_image'] ?>" />
            </div>
            <p><?php echo $p['full_content'] ?></p>
        </div>
    </div>
    <div class="rightcolumn">
        <div class="card">
            <h2>About Me</h2>
            <div class="fakeimg" style="height:100px;">Image</div>
            <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
        </div>
        <div class="card">
            <h3>Popular Post</h3>
            <div class="fakeimg">Image</div>
            <br>
            <div class="fakeimg">Image</div>
            <br>
            <div class="fakeimg">Image</div>
        </div>
    </div>
</div>
